### ISSUE TITLE
Multiple Apps With Nx Workspaces Router issue

### ISSUE THREAD

**Issue by AGelstein** [onehungrymind/fem-production-angular#1]
On the video Multiple Apps With Nx Workspaces when attempting to run `nx run client:serve ` I get the following error. I have pulled directly from the repo here and still get the issue.

![image](https://user-images.githubusercontent.com/6600605/131926511-e433d55b-e14c-4386-8dc7-924fe9945851.png)

**Comment by simpulton** [comment]
Issue has been fixed.
